CREATE TABLE IF NOT EXIST `meeting_actions` (
	`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`meeting_id` BIGINT,
	`user_id` BIGINT,
	`action_id` BIGINT,
	`description` TEXT, 
	`note` TEXT NULL,
	`is_active` TINYINT DEFAULT 1,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`deleted_at` TIMESTAMP NULL
) ENGINE=InnoDB DEFAULT UTF8;
