CREATE TABLE IF NOT EXIST `meetings` (
	`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(255),
	`project_id` BIGINT,
	`issue_number` INT NULL,
	`meeting_date` DATE,
	`start_time` TIME NULL,
	`end_time` TIME NULL,
	`location` VARCHAR(255) NULL,
	`overview` TEXT NULL,
	`objective` TEXT,
	`problem` TEXT NULL,
	`opportunity` TEXT NULL,
	`discussion` TEXT NULL,
	`conclusion` TEXT NULL,
	`comment` TEXT NULL,
	`status` ENUM('ON_HOLD', 'NEXT_SCHEDULE', 'FINISHED'),
	`next_schedule` DATE NULL,
	`next_schedule_topic` VARCHAR(255) NULL,
	`next_schedule_comment` VARCHAR(255) NULL,
	`recorder_id` BIGINT,
	`record_date` DATE NULL,
	`checker_id` BIGINT​​ NULL,
	`check_date` DATE NULL,
	`is_active` TINYINT DEFAULT 1,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`deleted_at` TIMESTAMP NULL
) ENGINE=InnoDB DEFAULT UTF8;
