CREATE TABLE IF NOT EXISTS `projects`(
	`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(255), 
	`project_purpose` TEXT NULL,
	`descriptions` TEXT NULL,
	`organization_id` BIGINT,
	`manager_id` BIGINT NULL,
	`start_date` DATE NULL,
	`end_date` DATE NULL,
	`is_active` TINYINT DEFAULT 1,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`deleted_at` TIMESTAMP NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
